// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: runtime.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeStatus int32

const (
	RuntimeStatus_CREATING   RuntimeStatus = 0
	RuntimeStatus_RUNNING    RuntimeStatus = 1
	RuntimeStatus_STOPPED    RuntimeStatus = 2
	RuntimeStatus_RESTARTING RuntimeStatus = 3
	RuntimeStatus_DELETED    RuntimeStatus = 4
	RuntimeStatus_FAILED     RuntimeStatus = 5
)

// Enum value maps for RuntimeStatus.
var (
	RuntimeStatus_name = map[int32]string{
		0: "CREATING",
		1: "RUNNING",
		2: "STOPPED",
		3: "RESTARTING",
		4: "DELETED",
		5: "FAILED",
	}
	RuntimeStatus_value = map[string]int32{
		"CREATING":   0,
		"RUNNING":    1,
		"STOPPED":    2,
		"RESTARTING": 3,
		"DELETED":    4,
		"FAILED":     5,
	}
)

func (x RuntimeStatus) Enum() *RuntimeStatus {
	p := new(RuntimeStatus)
	*p = x
	return p
}

func (x RuntimeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[0].Descriptor()
}

func (RuntimeStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[0]
}

func (x RuntimeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeStatus.Descriptor instead.
func (RuntimeStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_STARTING  HealthStatus = 0
	HealthStatus_HEALTHY   HealthStatus = 1
	HealthStatus_UNHEALTHY HealthStatus = 2
	HealthStatus_UNKNOWN   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "STARTING",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "UNKNOWN",
	}
	HealthStatus_value = map[string]int32{
		"STARTING":  0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"UNKNOWN":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_runtime_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

type ServicePlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,2,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	ExecuteRoute  string                 `protobuf:"bytes,3,opt,name=execute_route,json=executeRoute,proto3" json:"execute_route,omitempty"`
	HealthRoute   string                 `protobuf:"bytes,4,opt,name=health_route,json=healthRoute,proto3" json:"health_route,omitempty"`
	MetadataRoute string                 `protobuf:"bytes,5,opt,name=metadata_route,json=metadataRoute,proto3" json:"metadata_route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServicePlan) Reset() {
	*x = ServicePlan{}
	mi := &file_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePlan) ProtoMessage() {}

func (x *ServicePlan) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePlan.ProtoReflect.Descriptor instead.
func (*ServicePlan) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ServicePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServicePlan) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ServicePlan) GetExecuteRoute() string {
	if x != nil {
		return x.ExecuteRoute
	}
	return ""
}

func (x *ServicePlan) GetHealthRoute() string {
	if x != nil {
		return x.HealthRoute
	}
	return ""
}

func (x *ServicePlan) GetMetadataRoute() string {
	if x != nil {
		return x.MetadataRoute
	}
	return ""
}

type CreateRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeploymentId  string                 `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Framework     string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	BuildCommand  string                 `protobuf:"bytes,6,opt,name=build_command,json=buildCommand,proto3" json:"build_command,omitempty"`
	StartCommand  string                 `protobuf:"bytes,7,opt,name=start_command,json=startCommand,proto3" json:"start_command,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,8,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Services      []*ServicePlan         `protobuf:"bytes,9,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuntimeRequest) Reset() {
	*x = CreateRuntimeRequest{}
	mi := &file_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuntimeRequest) ProtoMessage() {}

func (x *CreateRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuntimeRequest.ProtoReflect.Descriptor instead.
func (*CreateRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRuntimeRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *CreateRuntimeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateRuntimeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateRuntimeRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *CreateRuntimeRequest) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *CreateRuntimeRequest) GetBuildCommand() string {
	if x != nil {
		return x.BuildCommand
	}
	return ""
}

func (x *CreateRuntimeRequest) GetStartCommand() string {
	if x != nil {
		return x.StartCommand
	}
	return ""
}

func (x *CreateRuntimeRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *CreateRuntimeRequest) GetServices() []*ServicePlan {
	if x != nil {
		return x.Services
	}
	return nil
}

type DeployedAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentUrl      string                 `protobuf:"bytes,2,opt,name=agent_url,json=agentUrl,proto3" json:"agent_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployedAgent) Reset() {
	*x = DeployedAgent{}
	mi := &file_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedAgent) ProtoMessage() {}

func (x *DeployedAgent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployedAgent.ProtoReflect.Descriptor instead.
func (*DeployedAgent) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *DeployedAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeployedAgent) GetAgentUrl() string {
	if x != nil {
		return x.AgentUrl
	}
	return ""
}

type CreateRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Status        RuntimeStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rcloud.runtime.RuntimeStatus" json:"status,omitempty"`
	Agents        []*DeployedAgent       `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuntimeResponse) Reset() {
	*x = CreateRuntimeResponse{}
	mi := &file_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuntimeResponse) ProtoMessage() {}

func (x *CreateRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuntimeResponse.ProtoReflect.Descriptor instead.
func (*CreateRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRuntimeResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *CreateRuntimeResponse) GetStatus() RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return RuntimeStatus_CREATING
}

func (x *CreateRuntimeResponse) GetAgents() []*DeployedAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type StopRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRuntimeRequest) Reset() {
	*x = StopRuntimeRequest{}
	mi := &file_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeRequest) ProtoMessage() {}

func (x *StopRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeRequest.ProtoReflect.Descriptor instead.
func (*StopRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *StopRuntimeRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *StopRuntimeRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type StopRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Status        RuntimeStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rcloud.runtime.RuntimeStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRuntimeResponse) Reset() {
	*x = StopRuntimeResponse{}
	mi := &file_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRuntimeResponse) ProtoMessage() {}

func (x *StopRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRuntimeResponse.ProtoReflect.Descriptor instead.
func (*StopRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *StopRuntimeResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *StopRuntimeResponse) GetStatus() RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return RuntimeStatus_CREATING
}

func (x *StopRuntimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestartRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRuntimeRequest) Reset() {
	*x = RestartRuntimeRequest{}
	mi := &file_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRuntimeRequest) ProtoMessage() {}

func (x *RestartRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRuntimeRequest.ProtoReflect.Descriptor instead.
func (*RestartRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *RestartRuntimeRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *RestartRuntimeRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type RestartRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Status        RuntimeStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rcloud.runtime.RuntimeStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRuntimeResponse) Reset() {
	*x = RestartRuntimeResponse{}
	mi := &file_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRuntimeResponse) ProtoMessage() {}

func (x *RestartRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRuntimeResponse.ProtoReflect.Descriptor instead.
func (*RestartRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *RestartRuntimeResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *RestartRuntimeResponse) GetStatus() RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return RuntimeStatus_CREATING
}

func (x *RestartRuntimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuntimeRequest) Reset() {
	*x = DeleteRuntimeRequest{}
	mi := &file_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuntimeRequest) ProtoMessage() {}

func (x *DeleteRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuntimeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRuntimeRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *DeleteRuntimeRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type DeleteRuntimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuntimeResponse) Reset() {
	*x = DeleteRuntimeResponse{}
	mi := &file_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuntimeResponse) ProtoMessage() {}

func (x *DeleteRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuntimeResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRuntimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRuntimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRuntimeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeStatusRequest) Reset() {
	*x = GetRuntimeStatusRequest{}
	mi := &file_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeStatusRequest) ProtoMessage() {}

func (x *GetRuntimeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeStatusRequest) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *GetRuntimeStatusRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *GetRuntimeStatusRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentUrl      string                 `protobuf:"bytes,2,opt,name=agent_url,json=agentUrl,proto3" json:"agent_url,omitempty"`
	Health        HealthStatus           `protobuf:"varint,3,opt,name=health,proto3,enum=rcloud.runtime.HealthStatus" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *AgentStatus) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatus) GetAgentUrl() string {
	if x != nil {
		return x.AgentUrl
	}
	return ""
}

func (x *AgentStatus) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_STARTING
}

type GetRuntimeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	Status        RuntimeStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rcloud.runtime.RuntimeStatus" json:"status,omitempty"`
	OverallHealth HealthStatus           `protobuf:"varint,3,opt,name=overall_health,json=overallHealth,proto3,enum=rcloud.runtime.HealthStatus" json:"overall_health,omitempty"`
	LastCheckedAt string                 `protobuf:"bytes,4,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	Agents        []*AgentStatus         `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeStatusResponse) Reset() {
	*x = GetRuntimeStatusResponse{}
	mi := &file_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeStatusResponse) ProtoMessage() {}

func (x *GetRuntimeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeStatusResponse) Descriptor() ([]byte, []int) {
	return file_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *GetRuntimeStatusResponse) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *GetRuntimeStatusResponse) GetStatus() RuntimeStatus {
	if x != nil {
		return x.Status
	}
	return RuntimeStatus_CREATING
}

func (x *GetRuntimeStatusResponse) GetOverallHealth() HealthStatus {
	if x != nil {
		return x.OverallHealth
	}
	return HealthStatus_STARTING
}

func (x *GetRuntimeStatusResponse) GetLastCheckedAt() string {
	if x != nil {
		return x.LastCheckedAt
	}
	return ""
}

func (x *GetRuntimeStatusResponse) GetAgents() []*AgentStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_runtime_proto protoreflect.FileDescriptor

const file_runtime_proto_rawDesc = "" +
	"\n" +
	"\rruntime.proto\x12\x0ercloud.runtime\"\xb0\x01\n" +
	"\vServicePlan\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x01(\tR\n" +
	"entrypoint\x12#\n" +
	"\rexecute_route\x18\x03 \x01(\tR\fexecuteRoute\x12!\n" +
	"\fhealth_route\x18\x04 \x01(\tR\vhealthRoute\x12%\n" +
	"\x0emetadata_route\x18\x05 \x01(\tR\rmetadataRoute\"\xbf\x03\n" +
	"\x14CreateRuntimeRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\tR\fdeploymentId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12#\n" +
	"\rbuild_command\x18\x06 \x01(\tR\fbuildCommand\x12#\n" +
	"\rstart_command\x18\a \x01(\tR\fstartCommand\x12W\n" +
	"\venvironment\x18\b \x03(\v25.rcloud.runtime.CreateRuntimeRequest.EnvironmentEntryR\venvironment\x127\n" +
	"\bservices\x18\t \x03(\v2\x1b.rcloud.runtime.ServicePlanR\bservices\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\rDeployedAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_url\x18\x02 \x01(\tR\bagentUrl\"\xa4\x01\n" +
	"\x15CreateRuntimeResponse\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.rcloud.runtime.RuntimeStatusR\x06status\x125\n" +
	"\x06agents\x18\x03 \x03(\v2\x1d.rcloud.runtime.DeployedAgentR\x06agents\"X\n" +
	"\x12StopRuntimeRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"\x85\x01\n" +
	"\x13StopRuntimeResponse\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.rcloud.runtime.RuntimeStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"[\n" +
	"\x15RestartRuntimeRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"\x88\x01\n" +
	"\x16RestartRuntimeResponse\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.rcloud.runtime.RuntimeStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Z\n" +
	"\x14DeleteRuntimeRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"K\n" +
	"\x15DeleteRuntimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x17GetRuntimeStatusRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\"{\n" +
	"\vAgentStatus\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tagent_url\x18\x02 \x01(\tR\bagentUrl\x124\n" +
	"\x06health\x18\x03 \x01(\x0e2\x1c.rcloud.runtime.HealthStatusR\x06health\"\x92\x02\n" +
	"\x18GetRuntimeStatusResponse\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.rcloud.runtime.RuntimeStatusR\x06status\x12C\n" +
	"\x0eoverall_health\x18\x03 \x01(\x0e2\x1c.rcloud.runtime.HealthStatusR\roverallHealth\x12&\n" +
	"\x0flast_checked_at\x18\x04 \x01(\tR\rlastCheckedAt\x123\n" +
	"\x06agents\x18\x05 \x03(\v2\x1b.rcloud.runtime.AgentStatusR\x06agents*`\n" +
	"\rRuntimeStatus\x12\f\n" +
	"\bCREATING\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\v\n" +
	"\aSTOPPED\x10\x02\x12\x0e\n" +
	"\n" +
	"RESTARTING\x10\x03\x12\v\n" +
	"\aDELETED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05*E\n" +
	"\fHealthStatus\x12\f\n" +
	"\bSTARTING\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x032\xec\x03\n" +
	"\x0eRuntimeService\x12\\\n" +
	"\rCreateRuntime\x12$.rcloud.runtime.CreateRuntimeRequest\x1a%.rcloud.runtime.CreateRuntimeResponse\x12V\n" +
	"\vStopRuntime\x12\".rcloud.runtime.StopRuntimeRequest\x1a#.rcloud.runtime.StopRuntimeResponse\x12_\n" +
	"\x0eRestartRuntime\x12%.rcloud.runtime.RestartRuntimeRequest\x1a&.rcloud.runtime.RestartRuntimeResponse\x12\\\n" +
	"\rDeleteRuntime\x12$.rcloud.runtime.DeleteRuntimeRequest\x1a%.rcloud.runtime.DeleteRuntimeResponse\x12e\n" +
	"\x10GetRuntimeStatus\x12'.rcloud.runtime.GetRuntimeStatusRequest\x1a(.rcloud.runtime.GetRuntimeStatusResponseB)Z'github.com/r-cloud/shared/proto/runtimeb\x06proto3"

var (
	file_runtime_proto_rawDescOnce sync.Once
	file_runtime_proto_rawDescData []byte
)

func file_runtime_proto_rawDescGZIP() []byte {
	file_runtime_proto_rawDescOnce.Do(func() {
		file_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)))
	})
	return file_runtime_proto_rawDescData
}

var file_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_runtime_proto_goTypes = []any{
	(RuntimeStatus)(0),               // 0: rcloud.runtime.RuntimeStatus
	(HealthStatus)(0),                // 1: rcloud.runtime.HealthStatus
	(*ServicePlan)(nil),              // 2: rcloud.runtime.ServicePlan
	(*CreateRuntimeRequest)(nil),     // 3: rcloud.runtime.CreateRuntimeRequest
	(*DeployedAgent)(nil),            // 4: rcloud.runtime.DeployedAgent
	(*CreateRuntimeResponse)(nil),    // 5: rcloud.runtime.CreateRuntimeResponse
	(*StopRuntimeRequest)(nil),       // 6: rcloud.runtime.StopRuntimeRequest
	(*StopRuntimeResponse)(nil),      // 7: rcloud.runtime.StopRuntimeResponse
	(*RestartRuntimeRequest)(nil),    // 8: rcloud.runtime.RestartRuntimeRequest
	(*RestartRuntimeResponse)(nil),   // 9: rcloud.runtime.RestartRuntimeResponse
	(*DeleteRuntimeRequest)(nil),     // 10: rcloud.runtime.DeleteRuntimeRequest
	(*DeleteRuntimeResponse)(nil),    // 11: rcloud.runtime.DeleteRuntimeResponse
	(*GetRuntimeStatusRequest)(nil),  // 12: rcloud.runtime.GetRuntimeStatusRequest
	(*AgentStatus)(nil),              // 13: rcloud.runtime.AgentStatus
	(*GetRuntimeStatusResponse)(nil), // 14: rcloud.runtime.GetRuntimeStatusResponse
	nil,                              // 15: rcloud.runtime.CreateRuntimeRequest.EnvironmentEntry
}
var file_runtime_proto_depIdxs = []int32{
	15, // 0: rcloud.runtime.CreateRuntimeRequest.environment:type_name -> rcloud.runtime.CreateRuntimeRequest.EnvironmentEntry
	2,  // 1: rcloud.runtime.CreateRuntimeRequest.services:type_name -> rcloud.runtime.ServicePlan
	0,  // 2: rcloud.runtime.CreateRuntimeResponse.status:type_name -> rcloud.runtime.RuntimeStatus
	4,  // 3: rcloud.runtime.CreateRuntimeResponse.agents:type_name -> rcloud.runtime.DeployedAgent
	0,  // 4: rcloud.runtime.StopRuntimeResponse.status:type_name -> rcloud.runtime.RuntimeStatus
	0,  // 5: rcloud.runtime.RestartRuntimeResponse.status:type_name -> rcloud.runtime.RuntimeStatus
	1,  // 6: rcloud.runtime.AgentStatus.health:type_name -> rcloud.runtime.HealthStatus
	0,  // 7: rcloud.runtime.GetRuntimeStatusResponse.status:type_name -> rcloud.runtime.RuntimeStatus
	1,  // 8: rcloud.runtime.GetRuntimeStatusResponse.overall_health:type_name -> rcloud.runtime.HealthStatus
	13, // 9: rcloud.runtime.GetRuntimeStatusResponse.agents:type_name -> rcloud.runtime.AgentStatus
	3,  // 10: rcloud.runtime.RuntimeService.CreateRuntime:input_type -> rcloud.runtime.CreateRuntimeRequest
	6,  // 11: rcloud.runtime.RuntimeService.StopRuntime:input_type -> rcloud.runtime.StopRuntimeRequest
	8,  // 12: rcloud.runtime.RuntimeService.RestartRuntime:input_type -> rcloud.runtime.RestartRuntimeRequest
	10, // 13: rcloud.runtime.RuntimeService.DeleteRuntime:input_type -> rcloud.runtime.DeleteRuntimeRequest
	12, // 14: rcloud.runtime.RuntimeService.GetRuntimeStatus:input_type -> rcloud.runtime.GetRuntimeStatusRequest
	5,  // 15: rcloud.runtime.RuntimeService.CreateRuntime:output_type -> rcloud.runtime.CreateRuntimeResponse
	7,  // 16: rcloud.runtime.RuntimeService.StopRuntime:output_type -> rcloud.runtime.StopRuntimeResponse
	9,  // 17: rcloud.runtime.RuntimeService.RestartRuntime:output_type -> rcloud.runtime.RestartRuntimeResponse
	11, // 18: rcloud.runtime.RuntimeService.DeleteRuntime:output_type -> rcloud.runtime.DeleteRuntimeResponse
	14, // 19: rcloud.runtime.RuntimeService.GetRuntimeStatus:output_type -> rcloud.runtime.GetRuntimeStatusResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_runtime_proto_init() }
func file_runtime_proto_init() {
	if File_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_proto_rawDesc), len(file_runtime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_proto_goTypes,
		DependencyIndexes: file_runtime_proto_depIdxs,
		EnumInfos:         file_runtime_proto_enumTypes,
		MessageInfos:      file_runtime_proto_msgTypes,
	}.Build()
	File_runtime_proto = out.File
	file_runtime_proto_goTypes = nil
	file_runtime_proto_depIdxs = nil
}
