package models

import "time"

// Deployment represents an execution and deployment release of a project.
type Deployment struct {
	ID          string     `json:"id"`
	ProjectID   string     `json:"projectId"`
	UserID      string     `json:"userId"`
	Branch      string     `json:"branch"`
	CommitHash  string     `json:"commitHash,omitempty"`
	Version     string     `json:"version,omitempty"`
	Mode        string     `json:"mode"`
	Status      string     `json:"status"`
	CreatedAt   time.Time  `json:"createdAt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
}

// ValidationResult represents the output from the Validation Service.
type ValidationResult struct {
	Valid  bool     `json:"valid"`
	Mode   string   `json:"mode,omitempty"`
	Agents []string `json:"agents,omitempty"`
	Errors []string `json:"errors,omitempty"`
}

// ServicePlan defines an individual agent/service configuration.
type ServicePlan struct {
	Name          string `json:"name"`
	Entrypoint    string `json:"entrypoint"`
	ExecuteRoute  string `json:"executeRoute"`
	HealthRoute   string `json:"healthRoute"`
	MetadataRoute string `json:"metadataRoute"`
}

// DeploymentPlan represents the full provider-specific plan generated by Deployment Planner.
type DeploymentPlan struct {
	Provider     string            `json:"provider"`
	Mode         string            `json:"mode"`
	Runtime      string            `json:"runtime"`
	Framework    string            `json:"framework"`
	BuildCommand string            `json:"buildCommand"`
	StartCommand string            `json:"startCommand"`
	Environment  map[string]string `json:"environment"`
	Services     []ServicePlan     `json:"services"`
}

// PlanRequest represents the incoming request to the Deployment Planner service.
type PlanRequest struct {
	ValidationResult ValidationResult  `json:"validationResult"`
	Environment      map[string]string `json:"environment"`
	Provider         string            `json:"provider"`
	Runtime          string            `json:"runtime"`
	Framework        string            `json:"framework"`
}
